services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garden
    ports:
      - "5432:5432"
    networks:
      - p-network
    volumes:
      - postgres-p-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "9193:9193"
    networks:
      - p-network

networks:
  p-network:
    driver: bridge

volumes:
  postgres-p-data: