version: '4'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garden
    ports:
      - "5432:5432"
    volumes:
      - postgres-i-data:/var/lib/postgresql/data